server:
  port: 5070

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka

  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ratel?characterEncoding=utf8&generateSimpleParameterMetadata=true&connectTimeout=5000&useSSL=false


zuul:
  host:
    socket-timeout-millis: 600000
    connect-timeout-millis: 600000
  routes:
    cloud-order:
      path: /order/**
      serviceId: cloud-order
      strip-prefix: false
      sensitiveHeaders: Access-Control-Allow-Origin,Access-Control-Allow-Methods
      ignoredPatterns: /order/test**

    cloud-user:
      path: /user/**
      serviceId: cloud-user
      strip-prefix: false
      sensitiveHeaders: Access-Control-Allow-Origin,Access-Control-Allow-Methods
      ignoredPatterns: /user/test**

  white-pattern: /user/inner/**,/order/inner/**