server:
  port: 5050
  servlet:
    context-path: /user

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka

  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

spring:
  application:
    name: cloud-user
  freemarker:
    enabled: false
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:postgresql://47.111.28.187:31432/ratel_company
    username: postgres
    password: postgres123!




