server:
  port: 5050
  servlet:
    context-path: /user

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka

  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

spring:
  application:
    name: cloud-user
  freemarker:
    enabled: false
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_user?characterEncoding=utf8&generateSimpleParameterMetadata=true&connectTimeout=5000&useSSL=false
    username: root
    password: root123

# logback.xml中有详细的日志配置
logging:
  config: classpath:logback.xml

#################################### Swagger start #################################
# swagger配置
swagger:
  base:
    package: yooo.yun.com
  contact:
    email: jiao.wang@yooo.yun
    name: wangjiao
    url: ''
  description: ''
  title: spring-demo
  url: ''
  version: 1.0
#################################### Swagger end ###################################




