server:
  port: 5050
  servlet:
    context-path: /user

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka

  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

spring:
  application:
    name: cloud-user
  freemarker:
    enabled: false
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_user?characterEncoding=utf8&generateSimpleParameterMetadata=true&connectTimeout=5000&useSSL=false
    username: root
    password: root123

# logback.xml中有详细的日志配置
logging:
  config: classpath:logback.xml
  #  方便Spring Boot Admin页面上实时查看日志
  file:
    path: logs/spring-boot-plus.log

# 打印SQL语句和结果集，本地开发环境可开启，线上注释掉
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl




